[autodetect_paths]
#The user should strictly follow the folder structure described in section 2.1 otherwise the paths will not be determined correctly. The parent folders should be named as: <scc_lidar_id>_<scc_version_id>_<scc_config_id>_<date>_<label>, with label being optional. The label can be anything describing the data, it can also be omitted. For example: '438_20250101' or '437_20230320_no_filter'
#main_data_folder (Mandatory field): The folder containing the parent folders and all other necessary information such as the configurations, settings, and radiosondes. These folders can be placed either directly in the main_data_folder or one directory level deeper. This can be achieved by using the scc_station_id field (explained below)
main_data_folder = 

#scc_station_id: The SCC station ID. Provide it if the parent folders must be placed under the <main_data_folder>/<station_id> directory. Leave empty if the parent folders must be placed placed in the <main_data_folder> directory
scc_station_id = 

#scc_configuration_id: The SCC configuration ID. It will be used for identifying the parent folder, the configuration files and the settings files. If not provided, the available configurations will be inferred from the existing parent folders and the user will be prompted to select one after running the calling script
scc_configuration_id =

#data_identifier: A unique pattern to identify the parent folder among folders that correspond to the same SCC configuration. Recommendation: Provide at least the date in yyyymmhh format. A custom label can be included as follows: <date>_<label> If not provided and there are more than 1 parent folders available with the same SCC configuration ID, the user will be prompted to provide one after running the calling script 
data_identifier =

#export_hoi_cfg: Select among 0, 1, or 2:
#               • 0: A local, manually created, configuration ini file will be used
#               • 1: The configuration ini file will be automatically created from the SCC handbook of instruments each time ATLAS runs. If atlas_configuration_file is provided in the explicit_paths and points to an existing configuration file, it will be overwritten. If the atlas_configuration_file is not provided in the explicit_paths the following file will be created: <stations_folder>/configurations/config_file_<scc_configuration_id>_exported.ini (if it already exists it will be overwritten). The exported file path will be used to point to the configuration file.
#               • 2: The configuration ini file will be automatically created from the SCC handbook of instruments similar to option 1 if there is no existing configuration file with the same path. If the file already exists, it will not be overwritten. Its path will be used to point to the configuration file.
# Note that an active internet connection is needed for options 1 and 2. If no connection is available the export_hoi_cfg will be automatically set to 0. In addition, currently K, special parallel and cross channel connections, and R_to_T_transmission_ratio parameters have to be provided manually if non-default values must be used in the [polarization_calibration] section of the configuration file.
# Using option 1 will result to a terminal prompt menu where the the user has to link each scc_channel_id with the recorder_channel_id. The same will happen with option 2 if the configuration file is not already exported. The atlas_channel_id will also be displayed to facilitate linking. The user can select to not link specific SCC channels and also to skip the process overall. Note that in the latter case the recorder_channel_id has to be provided manually
# Warning: Providing an existing atlas_configuration_file in the explicit_paths while the export_hoi_cfg is "1" will overwrite that specific file with the one exported from the SCC handbook of instruments
export_hoi_cfg = 

[explicit_paths]
#These paths can be provided if the default folder structure must be overridden. Providing the paths explicitly will deactivate the autodetect_paths process for this specific path (explicit paths always override autodetected paths). All paths of this section must be provided if the main_data_folder is not provided.
#Warning: Providing an existing atlas_configuration_file path with the export_hoi_cfg set to "1" will overwrite that specific file with the one exported from the SCC handbook of instruments

#parent_folder: Absolute path to the parent folder. Defaults to: None
parent_folder =

#atlas_configuration_file: Absolute path to the ATLAS configuration file. Defaults to: None
atlas_configuration_file =

#atlas_settings_file: Absolute  path to the ATLAS settings file. Defaults to: None
atlas_settings_file =

#radiosonde_folder: Absolute path to the folder that includes the radiosonde files. Defaults to: None
radiosonde_folder =

[general_options]
#quick_run: Defaults to False. If set to True the converter and the preprocessing modules will not be called if the algorithm detects output files already produced by them for a specific measurement. This mainly saves time during execution.
quick_run =

#process: The user can choose specific QA test(s) to process. Use any of: 
#               • ray: Rayleigh Fit
#               • tlc: Telecover Test
#               • pcb: Polarization Calibration
#               • drk: Long dark (used only for the quicklooks)
#               • off: No plots will be generated
#Defaults to: ray, tlc, pcb, drk
process =

#process_qck: Choose which quicklooks to process. It must be a subset of process. Note that each visualizer module (ray, tlc, pcb) can create their own quicklooks. Choose among 
#               • ray: Rayleigh Fit
#               • tlc: Telecover Test
#               • pcb: Polarization Calibration
#               • drk: Long dark 
#               • off: No quicklook plots will be generated
#Defaults to: ray, tlc, pcb, drk
process_qck =

#use_range: If set to False, the y axis units of all plots will correspond to the height in km above the lidar. If set to True, the y axis units corresponds to the range above the lidar. This variable determines the units of the following variables: 
#    • y_lims 
#    • z_max_zone
#    • smoothing_range
#Defaults to: True
use_range = 

#dpi: The dots per inch (dpi) resolution of the exported figures. Defaults to: 300 dpi 
dpi =

#output_folder: Provide it if the output folders generated by atlas (e.g. ascii, netcdf, html, reports) must be place in a separate directory. Defaults to: None
output_folder = 

#expert_analyst: Shortcut of the name of the person analyzing the data
expert_analyst =

#debug_signals: If set to True all signals and mask from all preprocessing stages will be saved to memory. Use with care as it can deplete the RAM. Defaults to False
debug_signals =

#export_netcdf: Export the raw and preprocessed signals and related metadata in netcdf format. Defaults to True
export_netcdf =

#export_all: Export all channels in the QA reports (e.g analog channels for Rayleigh fit test and photon channels for the telecover test). Defaults to False
export_all =

[filter_channels]
#channels: Provided it to process only selected channels. By default, no channel is excluded if this variable is not provided. The channel name must follow the nomenclature of section 4.3.
channels =

#exclude_telescope_type: Provide it to entirely exclude all channels of a specific telescope_type. By default, no channel is excluded if this variable is not provided. 
exclude_telescope_type =

#exclude_channel_type: Provide it to entirely exclude all channels of a specific channel_type. By default:
#    • if isday = False --> no channel is excluded if this variable is not provided
#    • if isday = True --> exclude_channel_type = v, f (vibrational Raman and fluorescence channels excluded)
exclude_channel_type =

#exclude_acquisition_mode: Provide it to entirely exclude all channels of a specific acquisition_mode. By default, no channel is excluded if this variable is not provided. 
exclude_acquisition_mode =

#exclude_channel_subtype: Provide it to entirely exclude all channels of a specific channel_subtype. By default, no channel is excluded if this variable is not provided. 
exclude_channel_subtype =

[trimming_options]
#max_height_agl: The maximum height km agl above which no calculations after background calculation will be performed. Solar background calculations are performed prior to vertical signal trimming to enable background calculations up to the maximum signal range. If the provided value is higher than the maximum available height of a channel, no trimming will be performed. Defaults to: 32.
max_height_agl =

#trim_overflows: This options determines how overflow values in the raw input files will be treated if detected. Choose among:
#    • 0: the algorithm will stop and provide a diagnostic error (default)
#    • 1: the files containing at least one overflow value will be screened out
#    • 2: overflows will be interpolated (use with care and only only a few bins per profile have overflow values)
#    • 3: overflows will not be excluded, use this only for debugging purposes
trim_overflows =

#max_adjacent_overflows: This option applies only if trim_overflows is set to 2. Adjacent overflows can be a risk for interpolation. If the number of adjacent bins with overflows is larger or equal to max_adjacent_overflows for even one channel, the signals from the whole file will be discarded. Defaults to: 5
max_adjacent_overflows =

#ray_averaging_rate: Averaging rate for the Rayleigh measurement. Provide either in hours or minutes in the following format: e.g. 10min --> 10 minutes, 2h --> 2 hours. If not provided or if the measurement is smaller than the provided averaging interval, the whole Rayleigh dataset will be averaged in a single profile. Otherwise, the Rayleigh measurement will be averaged in equal temporal intervals from the beginning to the end of the dataset. Profiles will be removed if more than 50% of the data are missing including gaps due to the slice_measurement and exclude measurement options, cloud screening, and overflow/low shot profile screening.  
ray_averaging_rate =

#ray_averaging_threshold: A threshold applied on the fraction of the profiles found within the time interval given by the rayleigh_averaging_rate (e.g. 10min) divided by the amount of expected profiles within the same interval based on the raw data temporal resolution. If the actual fraction for a certain average is smaller than the averaging threshold (e.g. due to cloud screening, missing data, low shots) the average will not be produced for that particular interval. Setting to 0. ensures that an average is always produced. Defaults to: 0.5 
ray_averaging_threshold =

#quicklook_averaging_rate: Similar to the ray_averaging_rate but applied to the Rayleigh measurement used for quicklooks (high resolution). Decimal values are also accepted: e.g. 0.5min --> 30 seconds, 0.5h --> 30 minutes
ray_qck_averaging_rate =

#ray_qck_averaging_threshold: Similar to the ray_averaging_threshold but applied to the Rayleigh measurement used for quicklooks (high resolution)
ray_qck_averaging_threshold =

#slice_measurement: Select a temporal region to process for one or more of the QA test measurements. Use an HHMM format for the time. Multiple regions can be defined. The test has to be specified first and then the start and stop time. This can be done multiple times for the same or more tests.  The following options are available for the tests: ray, ray_pcb, pcb, pcb_aux, tlc, tlc_rin, trg, dtm, nsf, drk, drk_ray, drk_ray_pcb, drk_pcb, drk_pcb_aux, drk_tlc, drk_tlc_rin, drk_trg, drk_dtm, drk_nsf
#For example: slice_measurement = ray, 2300, 0135, ray, 0215, 0410, drk, 0500, 0600 means that only Rayleigh measurements performed between 23:00 UTC and 01:35 UTC (the next day) and 02:15 and 04:10 UTC and also only long dark measurements performed betwenn 05:00 and 06:00 CET will be processed. Defaults to: None, None, None
slice_measurement =

#exclude_measurement: Select a temporal region to exclude (not process) for one or more of the QA test measurements. Use an HHMM format for the time. Multiple regions can be defined. The test has to be specified first and then the start and stop time. This can be done multiple times for the same or more tests.  The following options are available for the tests: ray, ray_pcb, pcb, pcb_aux, tlc, tlc_rin, trg, dtm, nsf, drk, drk_ray, drk_ray_pcb, drk_pcb, drk_pcb_aux, drk_tlc, drk_tlc_rin, drk_trg, drk_dtm, drk_nsf
#For example: exclude_measurement = ray, 2300, 0135, ray, 0215, 0410, drk, 0500, 0600 means that Rayleigh measurements performed between 23:00 UTC and 01:35 UTC (the next day) and 02:15 and 04:10 UTC and also long dark measurements performed betwenn 05:00 and 06:00 CET will not be processed. Defaults to: None, None, None
exclude_measurement =


[explicit_folders]
#These folder names have to be provided if the default parent folder structure must be overridden. Explicit names can be provided for any of the QA test folders. If provided, ATLAS will search for those specific folder name per test rather than the default names (e.g. nrm, tlc, tlc_rin, pcb, drk) in the parent folder. Provide only if it is necessary to deviate from the default ATLAS folder structure. This section is totally optional and can be omitted in the initialization file

#ray: Provide the name (string) of the folder with the Rayleigh measurement inside the parent folder (e.g. nrm_02). Defaults to: ray
ray =

#pcb: Provide the name (string) of the folder with the polarisation calibration measurement inside the parent folder (e.g. pcb_off)
pcb =

#tlc: Provide the name (string) of the folder with thee quadrant telecover test inside the parent folder (e.g. tlc_raman). Defaults to: tlc
tlc =

#tlc_rin: Provide the name (string) of the folder with the ring telecover test inside the parent folder (e.g. tlc_rin_raman). Defaults to: tlc_rin
tlc_rin =

#drk: Provide the name (string) of the folder with the long (or common short) dark measurement inside the parent folder (e.g. drk_day). Defaults to: drk
drk =

#trg: Provide the name (string) of the folder with the zero bin test inside the parent folder (e.g. trg_raman). Defaults to: trg
trg =

#dtm: Provide the name (string) of the folder with the dead time measurement inside the parent folder (e.g. dtm_02). Defaults to: dtm
dtm = 

#dtm: Provide the name (string) of the folder with the noise scaling factor inside the parent folder (e.g. nsf_02). Defaults to: nsf
nsf = 

#ray_pcb: Provide the name (string) of the folder with the Rayleigh measurement that will be used for the polarisation calibration (e.g. ray_cbm_02). Defaults to: ray
ray_pcb = 

#pcb_aux: Provide the name (string) of the folder with the auxiliary polarisation calibration measurement used to calculate the transmission of the ND filter used in front of the cross channel during calibration (e.g. pcb_nof). Defaults to pcb_aux
pcb_aux = 

#cam: Provide the name (string) of the folder with the alignment camera photos. Defaults to cam
cam =

[parsing_options]
#files_per_sector: The number of telecover files test per sector (integer). If provided, the telecover files must be placed in a single folder (this should be <path_to_parent_folder>/tlc according to the default folder structure). An automated assignment of the telecover files in different sectors will be attempted serially assuming the following temporal sequence of sectors: north – east – south – west. Note that the telecover test can have more than 1 rounds. Default to None
files_per_sector =

#files_per_ring: The number of telecover test files per ring (integer). If provided, the telecover files must be placed in a single folder (this should be <path_to_parent_folder>/tlc_rin according to the default folder structure). An automated assignment of the telecover files in different sectors will be attempted serially assuming the following temporal sequence of sectors: inner - outer. Note that the telecover test can have more than 1 rounds. Default to None
files_per_ring =

#files_per_set: The number of deadtime test files with and without attenuated signals. If provided, the dead time measurement files must be placed in a single folder (this should be <path_to_parent_folder>/dtm according to the default folder structure). An automated assignment of the deadtime files in different sets will be attempted serially assuming the following temporal sequence: not attenuated - attenuated. Note that the dead time test can have more than 1 rounds. Default to None
files_per_set =

#rsonde_skip_header: Radiosonde parser option. Number of lines to skip at the beginning of the radiosonde ascii file (integer). Defaults to: 1 (1 line reserved for header info)
rsonde_skip_header = 

#rsonde_skip_footer: Radiosonde parser option. Number of lines to skip at the end of the radiosonde file (integer). Defaults to: 0 (no footer assumed)
rsonde_skip_footer = 

#rsonde_delimiter: Radiosonde parser option. The delimiter that separates columns in the radiosonde file choose one of:
#    • S: space
#    • C: comma
#Defaults to: S.
rsonde_delimiter = 

#rsonde_column_index: Radiosonde parser option. The index (integer) of the column that contains the Height, Pressure, Temperature, and Relative Humidity (optional) information. For example, rsonde_columns = 2, 1, 3, 5 means: 
#    • Height: 2nd column in the radiosonde file 
#    • Pressure: 1st column 
#    • Temperature: 3rd column
#    • Relative Humidity: 5th column
#The relative humidity column is OPTIONAL and can be omitted. Defaults to: 2, 1, 3, 5
rsonde_column_index = 

#rsonde_column_units: Radiosonde parser option. The units (string) of Height, Pressure, Temperature, and Relative Humidity (optional) columns in the radiosonde file. The number of values must be the same as in rsonde_column_index. Supported units for:
#    • height: m_asl (default), km_asl, m_agl, km_agl
#    • pressure: hPa (default), Pa, atm
#    • temperature: K (default), C, Cx10
#    • relative humidity: percent (default), fraction
#If the Height units are in agl (above ground level) then the station altitude must be provided in the rsonde_geodata
rsonde_column_units = 

#rsonde_latitude: The radiosonde station latitude in degrees (float). Defaults to None
rsonde_latitude = 

#rsonde_longitude: The radiosonde station longitude in degrees (float). Defaults to None
rsonde_longitude = 

#rsonde_altitude: The radiosonde station altitude in meters (float). Mandatory if the radiosonde_column_units of the altitude is either m_agl or km_agl. In that case the lowermost altitude reported in the radiosonde file is used instead. Defaults to None.
rsonde_altitude = 

#rsonde_station_name: The name of the station where the radiosonde measurement was performed (string). Defaults to: None
rsonde_station_name = 

#rsonde_wmo_number: The WMO number of the radiosonde station (integer). Defaults to: None
rsonde_wmo_number = 
