#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the ATLAS intercomparison INI template and MkDocs reference page."""

from __future__ import annotations

import argparse
import html
from pathlib import Path
from typing import Any, Mapping

try:
    from atlas_actris.version import __version__ as ATLAS_VERSION
except Exception:
    ATLAS_VERSION = "unknown"

from atlas_actris.utils.parse_intercomparison_file import (
    GENERAL_SCHEMA, SYSTEM_SCHEMA, CHANNEL_SCHEMA, PAIR_SCHEMA,
)
from atlas_actris.templates.intercomparison_template_flavor import (
    GENERAL_TEMPLATE_KEYS, SYSTEM_TEMPLATE_KEYS, CHANNEL_TEMPLATE_KEYS,
    PAIR_TEMPLATE_KEYS, GENERAL_FLAVOR, SYSTEM_FLAVOR, CHANNEL_FLAVOR,
    PAIR_FLAVOR, SPECIAL_FLAVOR,
)

AUTO_SELECTION = "empty parameter --> ignored or automatic selection"


def _format_value(value: Any) -> str:
    if value is None or value == "" or value == []:
        return AUTO_SELECTION
    if isinstance(value, (list, tuple)):
        return ", ".join(str(item) for item in value)
    if isinstance(value, bool):
        return "True" if value else "False"
    return str(value)


def _allowed_display(meta: Mapping[str, Any]) -> str:
    parts: list[str] = []
    if "allowed" in meta:
        parts.append("Allowed values: " + ", ".join(str(value) for value in meta["allowed"]))
    if "min" in meta:
        parts.append(f"Minimum: {meta['min']}")
    if "max" in meta:
        parts.append(f"Maximum: {meta['max']}")
    if "size" in meta:
        parts.append(f"Required list size: {meta['size']}")
    return "; ".join(parts)


def _wrap(text: str, width: int = 88) -> list[str]:
    import textwrap
    return [f"# {line}" for line in textwrap.wrap(text, width=width)]


def _render_entry(
    key: str,
    meta: Mapping[str, Any],
    flavor: Mapping[str, Any],
    *,
    include_flavor: bool,
) -> str:
    if not include_flavor:
        return f"{key} ="

    lines = _wrap(str(flavor["description"]))
    allowed = _allowed_display(meta)
    if allowed:
        lines.extend(_wrap(allowed))
    lines.append(f"# Default: {_format_value(meta.get('default'))}")
    if flavor.get("example"):
        lines.append(f"# Example: {flavor['example']}")
    lines.append(f"{key} =")
    return "\n".join(lines)


def _header() -> str:
    return "\n".join([
        "# " + "=" * 76,
        "# ATLAS intercomparison initialization file template",
        "# " + "=" * 76,
        "#",
        f"# Generated by ATLAS {ATLAS_VERSION}",
        "#",
        "# Developers should not edit this generated file manually.",
        "# Update parse_intercomparison_file.py or intercomparison_template_flavor.py",
        "# and regenerate with: atlas-generate-intercomparison-template",
        "#",
        "# Users should copy this file and configure the repeated system/channel/pair",
        "# sections. Relative paths are resolved against this file's directory.",
        "#",
        "# " + "=" * 76,
        "",
    ])


def render_ini(*, include_flavor: bool = True) -> str:
    lines = [_header(), "[general]", ""]
    for key in GENERAL_TEMPLATE_KEYS:
        lines.extend([
            _render_entry(
                key, GENERAL_SCHEMA[key], GENERAL_FLAVOR[key],
                include_flavor=include_flavor,
            ),
            "",
        ])

    lines.extend([
        "",
        "# Repeat one [system:<system_id>] section per exported ATLAS system.",
        "[system:reference_system]", "",
    ])
    for key in SYSTEM_TEMPLATE_KEYS:
        lines.extend([
            _render_entry(
                key, SYSTEM_SCHEMA[key], SYSTEM_FLAVOR[key],
                include_flavor=include_flavor,
            ),
            "",
        ])

    lines.extend(["", "[system:system_b]", ""])
    for key in SYSTEM_TEMPLATE_KEYS:
        lines.extend([
            _render_entry(
                key, SYSTEM_SCHEMA[key], SYSTEM_FLAVOR[key],
                include_flavor=include_flavor,
            ),
            "",
        ])

    lines.extend([
        "",
        "# Repeat one [channel:<comparison_id>] section per channel bundle.",
        "[channel:355_parallel]", "",
    ])
    for key in CHANNEL_TEMPLATE_KEYS:
        lines.extend([
            _render_entry(
                key, CHANNEL_SCHEMA[key], CHANNEL_FLAVOR[key],
                include_flavor=include_flavor,
            ),
            "",
        ])

    if include_flavor:
        lines.extend([
            *(_wrap(SPECIAL_FLAVOR["system_channel_id"]["description"])),
            f"# Example: {SPECIAL_FLAVOR['system_channel_id']['example']}",
            "reference_system =", "",
            "system_b =", "",
            *(_wrap(SPECIAL_FLAVOR["system_signal_source"]["description"])),
            f"# Example: {SPECIAL_FLAVOR['system_signal_source']['example']}",
            "reference_system.signal_source =", "",
            "system_b.signal_source =", "",
            *(_wrap(SPECIAL_FLAVOR["system_signal_error_source"]["description"])),
            f"# Example: {SPECIAL_FLAVOR['system_signal_error_source']['example']}",
            "reference_system.signal_error_source =", "",
            "system_b.signal_error_source =", "",
        ])
    else:
        lines.extend([
            "reference_system =", "",
            "system_b =", "",
            "reference_system.signal_source =", "",
            "system_b.signal_source =", "",
            "reference_system.signal_error_source =", "",
            "system_b.signal_error_source =", "",
        ])

    lines.extend([
        "",
        "# Repeat one [pair:<comparison_id>] section per channel-pair bundle.",
        "[pair:vldr_355]", "",
    ])
    for key in PAIR_TEMPLATE_KEYS:
        lines.extend([
            _render_entry(
                key, PAIR_SCHEMA[key], PAIR_FLAVOR[key],
                include_flavor=include_flavor,
            ),
            "",
        ])

    if include_flavor:
        lines.extend([
            *(_wrap(SPECIAL_FLAVOR["system_pair_id"]["description"])),
            f"# Example: {SPECIAL_FLAVOR['system_pair_id']['example']}",
            "reference_system =", "",
            "system_b =", "",
            *(_wrap(SPECIAL_FLAVOR["system_pair_source"]["description"])),
            f"# Example: {SPECIAL_FLAVOR['system_pair_source']['example']}",
            "reference_system.pair_source =", "",
            "system_b.pair_source =", "",
            *(_wrap(SPECIAL_FLAVOR["system_pair_error_source"]["description"])),
            f"# Example: {SPECIAL_FLAVOR['system_pair_error_source']['example']}",
            "reference_system.pair_error_source =", "",
            "system_b.pair_error_source =", "",
        ])
    else:
        lines.extend([
            "reference_system =", "",
            "system_b =", "",
            "reference_system.pair_source =", "",
            "system_b.pair_source =", "",
            "reference_system.pair_error_source =", "",
            "system_b.pair_error_source =", "",
        ])

    return "\n".join(lines).rstrip() + "\n"


def render_bare_ini() -> str:
    return render_ini(include_flavor=False)


def _dtype(meta: Mapping[str, Any]) -> str:
    name = getattr(meta["dtype"], "__name__", str(meta["dtype"]))
    return f"list[{name}]" if meta.get("is_list") else name


def _md_table(schema: Mapping[str, Mapping[str, Any]], flavor: Mapping[str, Mapping[str, Any]], keys: list[str]) -> str:
    lines = [
        "| Parameter | Description | Type | Default | Allowed / limits | Example |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for key in keys:
        meta = schema[key]
        entry = flavor[key]
        values = [
            f"`{key}`",
            html.escape(str(entry["description"])).replace("|", "\\|"),
            f"`{_dtype(meta)}`",
            f"`{html.escape(_format_value(meta.get('default')))}`",
            html.escape(_allowed_display(meta)).replace("|", "\\|"),
            f"`{html.escape(str(entry.get('example', '')))}`" if entry.get("example") else "",
        ]
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def render_markdown() -> str:
    return "\n".join([
        "# ATLAS intercomparison initialization reference",
        "",
        '!!! note "Generated reference"',
        "    This page is generated from the intercomparison parser schemas and flavor text.",
        "",
        "## Structure",
        "",
        "The file contains one `[general]` section, repeated `[system:<id>]` sections, and repeated `[channel:<id>]` and `[pair:<id>]` comparison sections.",
        "",
        "Only one system may set `reference = True`. In every channel and pair section, the mapping for that reference system is mandatory. Missing non-reference system mappings inherit the reference system's data ID; `off` excludes a non-reference system.",
        "",
        "System-specific source overrides use dotted names such as `system_b.signal_source = derived_profile`. A missing source inherits the reference system's source, which in turn falls back to the corresponding general default.",
        "",
        "## `general`", "", _md_table(GENERAL_SCHEMA, GENERAL_FLAVOR, GENERAL_TEMPLATE_KEYS), "",
        "## `system:<system_id>`", "", _md_table(SYSTEM_SCHEMA, SYSTEM_FLAVOR, SYSTEM_TEMPLATE_KEYS), "",
        "## `channel:<comparison_id>`", "", _md_table(CHANNEL_SCHEMA, CHANNEL_FLAVOR, CHANNEL_TEMPLATE_KEYS), "",
        "### Dynamic channel entries", "",
        "- `<system_id> = <atlas_channel_id>` maps a system. The reference-system mapping is mandatory; omitted non-reference IDs inherit it; `off` excludes a non-reference system.",
        "- `<system_id>.signal_source` and `<system_id>.signal_error_source` override exported parameters. Missing values inherit the reference system and then the general defaults.",
        "",
        "## `pair:<comparison_id>`", "", _md_table(PAIR_SCHEMA, PAIR_FLAVOR, PAIR_TEMPLATE_KEYS), "",
        "### Dynamic pair entries", "",
        "- `<system_id> = <atlas_pair_id>` maps a system. The reference-system mapping is mandatory; omitted non-reference IDs inherit it; `off` excludes a non-reference system.",
        "- `<system_id>.pair_source` and `<system_id>.pair_error_source` override exported parameters. Missing values inherit the reference system and then the general defaults.",
        "",
        "## Deferred metadata defaults", "",
        "Empty system labels, background regions, and normalization regions may remain unresolved after parsing. They are resolved later from the reference system metadata, separately for every channel comparison.",
        "",
    ])


def _repo_root_from_this_file() -> Path:
    # src/atlas_actris/templates/generate_intercomparison_template.py -> repository root
    return Path(__file__).resolve().parents[3]


def build_outputs(repo_root: str | Path | None = None) -> dict[Path, str]:
    root = Path(repo_root).resolve() if repo_root else _repo_root_from_this_file()
    return {
        root / "src" / "atlas_actris" / "templates" / "intercomparison.ini": render_ini(),
        root / "docs" / "generated" / "intercomparison_reference.md": render_markdown(),
    }


def generate(repo_root: str | Path | None = None, *, check: bool = False) -> dict[Path, str]:
    outputs = build_outputs(repo_root)
    changed: list[Path] = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                changed.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if changed:
        raise SystemExit("Generated intercomparison files are out of date:\n" + "\n".join(str(path) for path in changed))
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=None)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    outputs = generate(args.repo_root, check=args.check)
    for path in outputs:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
