#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""User-facing flavor text for generated ATLAS INI templates.

This module is intentionally simple.  The parser schema remains the technical
source of truth for valid keys, types, defaults, mandatory/optional status, and
allowed values.  The dictionaries below provide only user-facing text used by
the template/documentation generator:

- description: short explanatory comment shown above the template entry.
- example: optional example value shown in templates and MkDocs.
- legacy: structured backward-compatibility information.

The legacy dictionary uses the following fields:

- status: one of "", "new", "unchanged", "renamed", "moved".
- introduced: ATLAS version where the current parameter/location was introduced.
- old_names: previous parameter names, if any.
- old_location: previous INI file/section if the parameter was moved.
- old_names_removed_in: ATLAS version where old names stopped being accepted.
- note: optional compatibility explanation.
"""

from __future__ import annotations

try:
    from atlas_actris.version import __version__ as ATLAS_VERSION
except Exception:  # pragma: no cover - fallback for standalone editing
    ATLAS_VERSION = "unknown"

# The generated template should report this ATLAS version in its header.
TEMPLATE_ATLAS_VERSION = ATLAS_VERSION

LEGACY_STATUS_VALUES = {"", "new", "unchanged", "renamed", "moved"}

SETTINGS_TEMPLATE_SECTIONS = {'qck': 'quicklooks',
 'qck_vldr': 'quicklooks_vldr',
 'ray': 'rayleigh_fit',
 'tlc': 'quadrant_telecover',
 'tlc_rin': 'ring_telecover',
 'pcb': 'polarization_calibration'}

SETTINGS_FLAVOR = {'qck': {'t_lims': {'description': 'Time limits used in the plot.',
                    'example': '2300, 0100',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         't_tick': {'description': 'Tick spacing for the time axis.',
                    'example': '30',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'x_lims': {'description': 'Horizontal-axis limits used in the plot.',
                    'example': '0, 14',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'x_tick': {'description': 'Horizontal-axis tick spacing.',
                    'example': '1',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'y_lims': {'description': 'Vertical-axis limits used in the plot.',
                    'example': '0, 1',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'y_max_zone': {'description': 'Zone used to define or display the maximum '
                                       'signal range.',
                        'example': '0.2, 1.0',
                        'legacy': {'status': '',
                                   'introduced': '',
                                   'old_names': [],
                                   'old_location': '',
                                   'old_names_removed_in': '',
                                   'note': ''}},
         'use_log_y_scale': {'description': 'Use a logarithmic vertical axis.',
                             'example': 'False',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'smooth': {'description': 'Apply smoothing before plotting or fitting.',
                    'example': 'True',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'smoothing_range': {'description': 'Height/range interval over which '
                                            'smoothing is applied.',
                             'example': '0.05, 15',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'smoothing_window': {'description': 'Smoothing window size.',
                              'example': '0.5',
                              'legacy': {'status': '',
                                         'introduced': '',
                                         'old_names': [],
                                         'old_location': '',
                                         'old_names_removed_in': '',
                                         'note': ''}},
         'smoothing_exponential': {'description': 'Use exponential smoothing window '
                                                  'behaviour.',
                                   'example': 'False',
                                   'legacy': {'status': '',
                                              'introduced': '',
                                              'old_names': [],
                                              'old_location': '',
                                              'old_names_removed_in': '',
                                              'note': ''}},
         'select_channels': {'description': 'Channel IDs to include explicitly.',
                              'example': '0532xcpr, 1064xtax',
                              'legacy': {'status': '',
                                         'introduced': '',
                                         'old_names': [],
                                         'old_location': '',
                                         'old_names_removed_in': '',
                                         'note': ''}},
         'exclude_wavelength': {'description': 'Wavelengths to exclude.',
                                'example': '1064',
                                'legacy': {'status': '',
                                           'introduced': '',
                                           'old_names': [],
                                           'old_location': '',
                                           'old_names_removed_in': '',
                                           'note': ''}},
         'exclude_telescope_type': {'description': 'Telescope types to exclude.',
                                    'example': 'n, f',
                                    'legacy': {'status': '',
                                               'introduced': '',
                                               'old_names': [],
                                               'old_location': '',
                                               'old_names_removed_in': '',
                                               'note': ''}},
         'exclude_channel_type': {'description': 'Channel types to exclude.',
                                  'example': 'a, f',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
         'exclude_acquisition_mode': {'description': 'Acquisition modes to exclude.',
                                      'example': 'a',
                                      'legacy': {'status': '',
                                                 'introduced': '',
                                                 'old_names': [],
                                                 'old_location': '',
                                                 'old_names_removed_in': '',
                                                 'note': ''}},
         'exclude_channel_subtype': {'description': 'Channel subtypes to exclude.',
                                     'example': 'w, c',
                                     'legacy': {'status': '',
                                                'introduced': '',
                                                'old_names': [],
                                                'old_location': '',
                                                'old_names_removed_in': '',
                                                'note': ''}}},
 'qck_vldr': {'t_lims': {'description': 'Time limits used in the plot.',
                         'example': '2300, 0100',
                         'legacy': {'status': '',
                                    'introduced': '',
                                    'old_names': [],
                                    'old_location': '',
                                    'old_names_removed_in': '',
                                    'note': ''}},
              't_tick': {'description': 'Tick spacing for the time axis.',
                         'example': '30',
                         'legacy': {'status': '',
                                    'introduced': '',
                                    'old_names': [],
                                    'old_location': '',
                                    'old_names_removed_in': '',
                                    'note': ''}},
              'x_lims': {'description': 'Horizontal-axis limits used in the plot.',
                         'example': '0, 14',
                         'legacy': {'status': '',
                                    'introduced': '',
                                    'old_names': [],
                                    'old_location': '',
                                    'old_names_removed_in': '',
                                    'note': ''}},
              'x_tick': {'description': 'Horizontal-axis tick spacing.',
                         'example': '1',
                         'legacy': {'status': '',
                                    'introduced': '',
                                    'old_names': [],
                                    'old_location': '',
                                    'old_names_removed_in': '',
                                    'note': ''}},
              'y_lims': {'description': 'Vertical-axis limits used in the plot.',
                         'example': '0, 1',
                         'legacy': {'status': '',
                                    'introduced': '',
                                    'old_names': [],
                                    'old_location': '',
                                    'old_names_removed_in': '',
                                    'note': ''}},
              'y_max_zone': {'description': 'Zone used to define or display the '
                                            'maximum signal range.',
                             'example': '0.2, 1.0',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
              'use_log_y_scale': {'description': 'Use a logarithmic vertical axis.',
                                  'example': 'False',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
              'smooth': {'description': 'Apply smoothing before plotting or fitting.',
                         'example': 'True',
                         'legacy': {'status': '',
                                    'introduced': '',
                                    'old_names': [],
                                    'old_location': '',
                                    'old_names_removed_in': '',
                                    'note': ''}},
              'smoothing_range': {'description': 'Height/range interval over which '
                                                 'smoothing is applied.',
                                  'example': '0.05, 15',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
              'smoothing_window': {'description': 'Smoothing window size.',
                                   'example': '0.5',
                                   'legacy': {'status': '',
                                              'introduced': '',
                                              'old_names': [],
                                              'old_location': '',
                                              'old_names_removed_in': '',
                                              'note': ''}},
              'smoothing_exponential': {'description': 'Use exponential smoothing '
                                                       'window behaviour.',
                                        'example': 'False',
                                        'legacy': {'status': '',
                                                   'introduced': '',
                                                   'old_names': [],
                                                   'old_location': '',
                                                   'old_names_removed_in': '',
                                                   'note': ''}},
              'include_pairs': {'description': 'Channel/pair IDs to include '
                                               'explicitly.',
                                'example': '0532xvax, 0532xvpx',
                                'legacy': {'status': '',
                                           'introduced': '',
                                           'old_names': [],
                                           'old_location': '',
                                           'old_names_removed_in': '',
                                           'note': ''}},
              'exclude_wavelength': {'description': 'Wavelengths to exclude.',
                                     'example': '1064',
                                     'legacy': {'status': '',
                                                'introduced': '',
                                                'old_names': [],
                                                'old_location': '',
                                                'old_names_removed_in': '',
                                                'note': ''}},
              'exclude_telescope_type': {'description': 'Telescope types to exclude.',
                                         'example': 'n, f',
                                         'legacy': {'status': '',
                                                    'introduced': '',
                                                    'old_names': [],
                                                    'old_location': '',
                                                    'old_names_removed_in': '',
                                                    'note': ''}},
              'exclude_pair_type': {'description': 'Pair/channel types to exclude.',
                                    'example': 'a, f',
                                    'legacy': {'status': '',
                                               'introduced': '',
                                               'old_names': [],
                                               'old_location': '',
                                               'old_names_removed_in': '',
                                               'note': ''}},
              'exclude_acquisition_mode': {'description': 'Acquisition modes to '
                                                          'exclude.',
                                           'example': 'a',
                                           'legacy': {'status': '',
                                                      'introduced': '',
                                                      'old_names': [],
                                                      'old_location': '',
                                                      'old_names_removed_in': '',
                                                      'note': ''}},
              'exclude_channel_subtype': {'description': 'Channel subtypes to exclude.',
                                          'example': 'w, c',
                                          'legacy': {'status': '',
                                                     'introduced': '',
                                                     'old_names': [],
                                                     'old_location': '',
                                                     'old_names_removed_in': '',
                                                     'note': ''}}},
 'ray': {'x_lims': {'description': 'Horizontal-axis limits used in the plot.',
                    'example': '0, 14',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'x_tick': {'description': 'Horizontal-axis tick spacing.',
                    'example': '1',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'y_lims': {'description': 'Vertical-axis limits used in the plot.',
                    'example': '0, 1',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'use_lin_y_scale': {'description': 'Force a linear vertical axis.',
                             'example': 'False',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'normalization_region': {'description': 'Height/range interval used for '
                                                 'signal normalization.',
                                  'example': '6, 8',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
         'molecular_mask_region': {'description': 'Height/range interval searched for '
                                                  'molecular-mask candidates.',
                                   'example': '2, 34',
                                   'legacy': {'status': '',
                                              'introduced': '',
                                              'old_names': [],
                                              'old_location': '',
                                              'old_names_removed_in': '',
                                              'note': ''}},
         'molecular_mask_window': {'description': 'Minimum and maximum window size '
                                                  'used for molecular-mask tests.',
                                   'example': '0.5, 4',
                                   'legacy': {'status': '',
                                              'introduced': '',
                                              'old_names': [],
                                              'old_location': '',
                                              'old_names_removed_in': '',
                                              'note': ''}},
         'molecular_mask_window_step': {'description': 'Step size used when scanning '
                                                       'molecular-mask windows.',
                                        'example': '0.2',
                                        'legacy': {'status': '',
                                                   'introduced': '',
                                                   'old_names': [],
                                                   'old_location': '',
                                                   'old_names_removed_in': '',
                                                   'note': ''}},
         'rsem_threshold': {'description': 'Relative standard error threshold used in '
                                           'the Rayleigh-fit mask.',
                            'example': '0.025',
                            'legacy': {'status': '',
                                       'introduced': '',
                                       'old_names': [],
                                       'old_location': '',
                                       'old_names_removed_in': '',
                                       'note': ''}},
         'first_derivative_threshold': {'description': 'First-derivative threshold '
                                                       'used in the Rayleigh-fit mask.',
                                        'example': '2.0',
                                        'legacy': {'status': '',
                                                   'introduced': '',
                                                   'old_names': [],
                                                   'old_location': '',
                                                   'old_names_removed_in': '',
                                                   'note': ''}},
         'second_derivative_threshold': {'description': 'Second-derivative threshold '
                                                        'used in the Rayleigh-fit '
                                                        'mask.',
                                         'example': '2.0',
                                         'legacy': {'status': '',
                                                    'introduced': '',
                                                    'old_names': [],
                                                    'old_location': '',
                                                    'old_names_removed_in': '',
                                                    'note': ''}},
         'shapiro_wilk_threshold': {'description': 'Shapiro-Wilk normality threshold '
                                                   'used in the Rayleigh-fit mask.',
                                    'example': '0.05',
                                    'legacy': {'status': '',
                                               'introduced': '',
                                               'old_names': [],
                                               'old_location': '',
                                               'old_names_removed_in': '',
                                               'note': ''}},
         'cross_criterion_threshold': {'description': 'Cross-criterion threshold used '
                                                      'in the Rayleigh-fit mask.',
                                       'example': '1.0',
                                       'legacy': {'status': '',
                                                  'introduced': '',
                                                  'old_names': [],
                                                  'old_location': '',
                                                  'old_names_removed_in': '',
                                                  'note': ''}},
         'durbin_watson_threshold': {'description': 'Accepted Durbin-Watson interval '
                                                    'used in the Rayleigh-fit mask.',
                                     'example': '1, 3',
                                     'legacy': {'status': '',
                                                'introduced': '',
                                                'old_names': [],
                                                'old_location': '',
                                                'old_names_removed_in': '',
                                                'note': ''}},
         'absolute_extinction_error_threshold': {'description': 'Maximum accepted '
                                                                'absolute extinction '
                                                                'error.',
                                                 'example': '10',
                                                 'legacy': {'status': '',
                                                            'introduced': '',
                                                            'old_names': [],
                                                            'old_location': '',
                                                            'old_names_removed_in': '',
                                                            'note': ''}},
         'isolated_point_radius': {'description': 'Neighbourhood radius used to detect '
                                                  'isolated valid mask points.',
                                   'example': '2',
                                   'legacy': {'status': '',
                                              'introduced': '',
                                              'old_names': [],
                                              'old_location': '',
                                              'old_names_removed_in': '',
                                              'note': ''}},
         'isolated_point_neighbour_threshold': {'description': 'Minimum number of '
                                                               'neighbours required to '
                                                               'keep a mask point.',
                                                'example': '2',
                                                'legacy': {'status': '',
                                                           'introduced': '',
                                                           'old_names': [],
                                                           'old_location': '',
                                                           'old_names_removed_in': '',
                                                           'note': ''}},
         'smooth': {'description': 'Apply smoothing before plotting or fitting.',
                    'example': 'True',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'smoothing_range': {'description': 'Height/range interval over which '
                                            'smoothing is applied.',
                             'example': '0.05, 15',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'smoothing_window': {'description': 'Smoothing window size.',
                              'example': '0.5',
                              'legacy': {'status': '',
                                         'introduced': '',
                                         'old_names': [],
                                         'old_location': '',
                                         'old_names_removed_in': '',
                                         'note': ''}},
         'select_channels': {'description': 'Channel IDs to include explicitly.',
                              'example': '0532xcpr, 1064xtax',
                              'legacy': {'status': '',
                                         'introduced': '',
                                         'old_names': [],
                                         'old_location': '',
                                         'old_names_removed_in': '',
                                         'note': ''}},
         'exclude_wavelength': {'description': 'Wavelengths to exclude.',
                                'example': '1064',
                                'legacy': {'status': '',
                                           'introduced': '',
                                           'old_names': [],
                                           'old_location': '',
                                           'old_names_removed_in': '',
                                           'note': ''}},
         'exclude_telescope_type': {'description': 'Telescope types to exclude.',
                                    'example': 'n, f',
                                    'legacy': {'status': '',
                                               'introduced': '',
                                               'old_names': [],
                                               'old_location': '',
                                               'old_names_removed_in': '',
                                               'note': ''}},
         'exclude_channel_type': {'description': 'Channel types to exclude.',
                                  'example': 'a, f',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
         'exclude_acquisition_mode': {'description': 'Acquisition modes to exclude.',
                                      'example': 'a',
                                      'legacy': {'status': '',
                                                 'introduced': '',
                                                 'old_names': [],
                                                 'old_location': '',
                                                 'old_names_removed_in': '',
                                                 'note': ''}},
         'exclude_channel_subtype': {'description': 'Channel subtypes to exclude.',
                                     'example': 'w, c',
                                     'legacy': {'status': '',
                                                'introduced': '',
                                                'old_names': [],
                                                'old_location': '',
                                                'old_names_removed_in': '',
                                                'note': ''}}},
 'tlc': {'plot_raw_signals': {'description': 'Plot raw telecover signals in '
                                                 'addition to processed signals.',
                                  'example': 'False',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
             'use_last_sector': {'description': 'Use the last telecover sector/ring as '
                                                'the reference sector when enabled.',
                                 'example': 'False',
                                 'legacy': {'status': '',
                                            'introduced': '',
                                            'old_names': [],
                                            'old_location': '',
                                            'old_names_removed_in': '',
                                            'note': ''}},
             'normalization_region': {'description': 'Height/range interval used for '
                                                     'signal normalization.',
                                      'example': '6, 8',
                                      'legacy': {'status': '',
                                                 'introduced': '',
                                                 'old_names': [],
                                                 'old_location': '',
                                                 'old_names_removed_in': '',
                                                 'note': ''}},
             'relative_deviation_limit': {'description': 'Relative deviation limit '
                                                         'used for telecover quality '
                                                         'checks.',
                                          'example': '0.05',
                                          'legacy': {'status': '',
                                                     'introduced': '',
                                                     'old_names': [],
                                                     'old_location': '',
                                                     'old_names_removed_in': '',
                                                     'note': ''}},
             'near_range_upper_limit': {'description': 'Upper limit of the near-range '
                                                       'interval.',
                                        'example': '2.5',
                                        'legacy': {'status': '',
                                                   'introduced': '',
                                                   'old_names': [],
                                                   'old_location': '',
                                                   'old_names_removed_in': '',
                                                   'note': ''}},
             'smooth': {'description': 'Apply smoothing before plotting or fitting.',
                        'example': 'True',
                        'legacy': {'status': '',
                                   'introduced': '',
                                   'old_names': [],
                                   'old_location': '',
                                   'old_names_removed_in': '',
                                   'note': ''}},
             'smoothing_window': {'description': 'Smoothing window size.',
                                  'example': '0.5',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
             'select_channels': {'description': 'Channel IDs to include explicitly.',
                                  'example': '0532xcpr, 1064xtax',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
             'exclude_wavelength': {'description': 'Wavelengths to exclude.',
                                    'example': '1064',
                                    'legacy': {'status': '',
                                               'introduced': '',
                                               'old_names': [],
                                               'old_location': '',
                                               'old_names_removed_in': '',
                                               'note': ''}},
             'exclude_telescope_type': {'description': 'Telescope types to exclude.',
                                        'example': 'n, f',
                                        'legacy': {'status': '',
                                                   'introduced': '',
                                                   'old_names': [],
                                                   'old_location': '',
                                                   'old_names_removed_in': '',
                                                   'note': ''}},
             'exclude_channel_type': {'description': 'Channel types to exclude.',
                                      'example': 'a, f',
                                      'legacy': {'status': '',
                                                 'introduced': '',
                                                 'old_names': [],
                                                 'old_location': '',
                                                 'old_names_removed_in': '',
                                                 'note': ''}},
             'exclude_acquisition_mode': {'description': 'Acquisition modes to '
                                                         'exclude.',
                                          'example': 'a',
                                          'legacy': {'status': '',
                                                     'introduced': '',
                                                     'old_names': [],
                                                     'old_location': '',
                                                     'old_names_removed_in': '',
                                                     'note': ''}},
             'exclude_channel_subtype': {'description': 'Channel subtypes to exclude.',
                                         'example': 'w, c',
                                         'legacy': {'status': '',
                                                    'introduced': '',
                                                    'old_names': [],
                                                    'old_location': '',
                                                    'old_names_removed_in': '',
                                                    'note': ''}}},
 'tlc_rin': {'plot_raw_signals': {'description': 'Plot raw telecover signals in '
                                                 'addition to processed signals.',
                                  'example': 'False',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
             'use_last_sector': {'description': 'Use the last telecover sector/ring as '
                                                'the reference sector when enabled.',
                                 'example': 'False',
                                 'legacy': {'status': '',
                                            'introduced': '',
                                            'old_names': [],
                                            'old_location': '',
                                            'old_names_removed_in': '',
                                            'note': ''}},
             'normalization_region': {'description': 'Height/range interval used for '
                                                     'signal normalization.',
                                      'example': '6, 8',
                                      'legacy': {'status': '',
                                                 'introduced': '',
                                                 'old_names': [],
                                                 'old_location': '',
                                                 'old_names_removed_in': '',
                                                 'note': ''}},
             'relative_deviation_limit': {'description': 'Relative deviation limit '
                                                         'used for telecover quality '
                                                         'checks.',
                                          'example': '0.05',
                                          'legacy': {'status': '',
                                                     'introduced': '',
                                                     'old_names': [],
                                                     'old_location': '',
                                                     'old_names_removed_in': '',
                                                     'note': ''}},
             'near_range_upper_limit': {'description': 'Upper limit of the near-range '
                                                       'interval.',
                                        'example': '2.5',
                                        'legacy': {'status': '',
                                                   'introduced': '',
                                                   'old_names': [],
                                                   'old_location': '',
                                                   'old_names_removed_in': '',
                                                   'note': ''}},
             'smooth': {'description': 'Apply smoothing before plotting or fitting.',
                        'example': 'True',
                        'legacy': {'status': '',
                                   'introduced': '',
                                   'old_names': [],
                                   'old_location': '',
                                   'old_names_removed_in': '',
                                   'note': ''}},
             'smoothing_window': {'description': 'Smoothing window size.',
                                  'example': '0.5',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
             'select_channels': {'description': 'Channel IDs to include explicitly.',
                                  'example': '0532xcpr, 1064xtax',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
             'exclude_wavelength': {'description': 'Wavelengths to exclude.',
                                    'example': '1064',
                                    'legacy': {'status': '',
                                               'introduced': '',
                                               'old_names': [],
                                               'old_location': '',
                                               'old_names_removed_in': '',
                                               'note': ''}},
             'exclude_telescope_type': {'description': 'Telescope types to exclude.',
                                        'example': 'n, f',
                                        'legacy': {'status': '',
                                                   'introduced': '',
                                                   'old_names': [],
                                                   'old_location': '',
                                                   'old_names_removed_in': '',
                                                   'note': ''}},
             'exclude_channel_type': {'description': 'Channel types to exclude.',
                                      'example': 'a, f',
                                      'legacy': {'status': '',
                                                 'introduced': '',
                                                 'old_names': [],
                                                 'old_location': '',
                                                 'old_names_removed_in': '',
                                                 'note': ''}},
             'exclude_acquisition_mode': {'description': 'Acquisition modes to '
                                                         'exclude.',
                                          'example': 'a',
                                          'legacy': {'status': '',
                                                     'introduced': '',
                                                     'old_names': [],
                                                     'old_location': '',
                                                     'old_names_removed_in': '',
                                                     'note': ''}},
             'exclude_channel_subtype': {'description': 'Channel subtypes to exclude.',
                                         'example': 'w, c',
                                         'legacy': {'status': '',
                                                    'introduced': '',
                                                    'old_names': [],
                                                    'old_location': '',
                                                    'old_names_removed_in': '',
                                                    'note': ''}}},
 'pcb': {'x_lims_signals': {'description': 'Horizontal-axis limits for '
                                           'polarization-calibration signal plots.',
                            'example': '0, 8',
                            'legacy': {'status': '',
                                       'introduced': '',
                                       'old_names': [],
                                       'old_location': '',
                                       'old_names_removed_in': '',
                                       'note': ''}},
         'x_tick_signals': {'description': 'Horizontal-axis tick spacing for signal '
                                           'plots.',
                            'example': '1',
                            'legacy': {'status': '',
                                       'introduced': '',
                                       'old_names': [],
                                       'old_location': '',
                                       'old_names_removed_in': '',
                                       'note': ''}},
         'y_lims_signals': {'description': 'Vertical-axis limits for signal plots.',
                            'example': '0, 1',
                            'legacy': {'status': '',
                                       'introduced': '',
                                       'old_names': [],
                                       'old_location': '',
                                       'old_names_removed_in': '',
                                       'note': ''}},
         'x_lims_calibration': {'description': 'Horizontal-axis limits for calibration '
                                               'plots.',
                                'example': '0, 8',
                                'legacy': {'status': '',
                                           'introduced': '',
                                           'old_names': [],
                                           'old_location': '',
                                           'old_names_removed_in': '',
                                           'note': ''}},
         'x_tick_calibration': {'description': 'Horizontal-axis tick spacing for '
                                               'calibration plots.',
                                'example': '1',
                                'legacy': {'status': '',
                                           'introduced': '',
                                           'old_names': [],
                                           'old_location': '',
                                           'old_names_removed_in': '',
                                           'note': ''}},
         'y_lims_calibration': {'description': 'Vertical-axis limits for calibration '
                                               'plots.',
                                'example': '0, 1',
                                'legacy': {'status': '',
                                           'introduced': '',
                                           'old_names': [],
                                           'old_location': '',
                                           'old_names_removed_in': '',
                                           'note': ''}},
         'x_lims_rayleigh': {'description': 'Horizontal-axis limits for Rayleigh '
                                            'comparison plots.',
                             'example': '0, 20',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'x_tick_rayleigh': {'description': 'Horizontal-axis tick spacing for Rayleigh '
                                            'comparison plots.',
                             'example': '2',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'y_lims_rayleigh': {'description': 'Vertical-axis limits for Rayleigh '
                                            'comparison plots.',
                             'example': '0, 1',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'calibration_region': {'description': 'Height/range interval used for '
                                               'polarization calibration.',
                                'example': '2, 4',
                                'legacy': {'status': '',
                                           'introduced': '',
                                           'old_names': [],
                                           'old_location': '',
                                           'old_names_removed_in': '',
                                           'note': ''}},
         'rayleigh_region': {'description': 'Height/range interval used for Rayleigh '
                                            'reference comparison.',
                             'example': '6, 8',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'pldr_error_threshold': {'description': 'Allowed PLDR uncertainty threshold.',
                                  'example': '0.025',
                                  'legacy': {'status': '',
                                             'introduced': '',
                                             'old_names': [],
                                             'old_location': '',
                                             'old_names_removed_in': '',
                                             'note': ''}},
         'smooth': {'description': 'Apply smoothing before plotting or fitting.',
                    'example': 'True',
                    'legacy': {'status': '',
                               'introduced': '',
                               'old_names': [],
                               'old_location': '',
                               'old_names_removed_in': '',
                               'note': ''}},
         'smoothing_range': {'description': 'Height/range interval over which '
                                            'smoothing is applied.',
                             'example': '0.05, 15',
                             'legacy': {'status': '',
                                        'introduced': '',
                                        'old_names': [],
                                        'old_location': '',
                                        'old_names_removed_in': '',
                                        'note': ''}},
         'smoothing_window': {'description': 'Smoothing window size.',
                              'example': '0.5',
                              'legacy': {'status': '',
                                         'introduced': '',
                                         'old_names': [],
                                         'old_location': '',
                                         'old_names_removed_in': '',
                                         'note': ''}},
         'smoothing_exponential': {'description': 'Use exponential smoothing window '
                                                  'behaviour.',
                                   'example': 'False',
                                   'legacy': {'status': '',
                                              'introduced': '',
                                              'old_names': [],
                                              'old_location': '',
                                              'old_names_removed_in': '',
                                              'note': ''}}}}


# Dark-test settings added with the corresponding parser schema. Existing
# flavor entries above are intentionally left unchanged.
SETTINGS_TEMPLATE_SECTIONS["drk"] = "dark"
SETTINGS_FLAVOR["drk"] = {
    "stats_range": {
        "description": "Height/range interval used to calculate dark-signal statistics.",
        "example": "5, 15",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "far_range_region": {
        "description": "Far-range interval used for the dark-signal quality check.",
        "example": "25, _",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "averaging_period": {
        "description": "Select the signal averaging level used by the dark test.",
        "example": "high_res",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "relative_molecular_deviation": {
        "description": "Maximum relative molecular-signal deviation accepted by the dark test.",
        "example": "0.01",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "smooth": {
        "description": "Apply smoothing to the dark signal before plotting or evaluation.",
        "example": "True",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "smoothing_range": {
        "description": "Height/range interval over which dark-signal smoothing is applied.",
        "example": "5, 15",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "smoothing_window": {
        "description": "Smoothing window size used for the dark signal.",
        "example": "0.5",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "smooth_rc": {
        "description": "Apply smoothing to the range-corrected dark signal.",
        "example": "True",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "smoothing_range_rc": {
        "description": "Height/range interval over which range-corrected dark-signal smoothing is applied.",
        "example": "0.05, 35",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "smoothing_window_rc": {
        "description": "Smoothing window size used for the range-corrected dark signal.",
        "example": "2",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "select_channels": {
        "description": "Channel IDs to include explicitly in the dark test.",
        "example": "0532xcpr, 1064xtax",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "exclude_wavelength": {
        "description": "Wavelengths to exclude from the dark test.",
        "example": "1064",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "exclude_telescope_type": {
        "description": "Telescope types to exclude from the dark test.",
        "example": "n, f",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "exclude_channel_type": {
        "description": "Channel types to exclude from the dark test.",
        "example": "a, f",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "exclude_acquisition_mode": {
        "description": "Acquisition modes to exclude from the dark test.",
        "example": "a",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
    "exclude_channel_subtype": {
        "description": "Channel subtypes to exclude from the dark test.",
        "example": "w, c",
        "legacy": {"status": "new", "introduced": "1.0.1", "old_names": [], "old_location": "", "old_names_removed_in": "", "note": ""},
    },
}
