#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Single source of truth for generated-template contents and ordering.

Every list below is an explicit subset of its parser schema.  Add or remove a
name here to expose or hide it in a generated template; do not change a parser
schema or a flavor file merely to change template contents.

Schemas own parsing metadata (type, default, limits).  Flavor modules own only
user-facing descriptions and examples.  This module owns INI sections,
parameter selection, and ordering.
"""

from __future__ import annotations

from pathlib import Path


# Generated artifacts live outside the importable source tree.
GENERATED_TEMPLATES_DIRECTORY = Path("templates")


# Full initialization template. Section names must also be accepted by the
# initialization parser; parameter names must exist in parse_init_file.SCHEMA.
INIT_TEMPLATE_SECTIONS = {
    "configuration": [
        "scc_compatible_format",
        "export_hoi_cfg",
        "scc_configuration_id",
    ],
    "explicit_paths": [
        "parent_folder",
        "atlas_configuration_file",
        "atlas_settings_file",
        "radiosonde_folder",
        "radiosonde_file",
        "output_folder",
    ],
    "general_options": [
        "process",
        "process_qck",
        "process_bgd",
        "process_vldr",
        "process_dedicated_dark",
        "vertical_scale",
        "view_mean_signal_stages",
        "view_signal_stages",
        "dpi",
        "color_reduction",
        "overwrite_output",
        "expert_analyst",
        "export_stages",
        "export_all",
    ],
    "filter_channels": [
        "select_channels",
        "exclude_wavelength",
        "exclude_telescope_type",
        "exclude_channel_type",
        "exclude_acquisition_mode",
        "exclude_channel_subtype",
    ],
    "trimming_options": [
        "max_height_agl",
        "low_shot_threshold",
        "trim_overflows",
        "low_res_averaging_period",
        "low_res_averaging_threshold",
        "high_res_averaging_period",
        "high_res_averaging_threshold",
        "max_adjacent_overflows",
        "slice_measurement",
        "exclude_measurement",
    ],
    "explicit_folders": [
        "ray",
        "pcb",
        "tlc",
        "tlc_rin",
        "drk",
        "trg",
        "dtm",
        "ray_pcb",
        "pcb_aux",
        "cam",
    ],
    "parsing_options": [
        "files_per_quadrant",
        "files_per_ring",
        "rsonde_skip_header",
        "rsonde_skip_footer",
        "rsonde_delimiter",
        "rsonde_column_index",
        "rsonde_column_units",
        "rsonde_station_altitude",
        "cloudnet_station_name",
        "rsonde_station_name",
        "rsonde_station_wmo_id",
    ],
}


# Full configuration template.
CONFIG_TEMPLATE_SECTIONS = {
    "System": [
        "station_id",
        "lidar_name",
        "station_name",
        "lidar_id",
        "version_name",
        "version_id",
        "configuration_name",
        "configuration_id",
        "station_altitude",
        "station_latitude",
        "station_longitude",
        "zenith_angle",
        "azimuth_angle",
    ],
    "Channels": [
        "recorder_channel_id",
        "scc_channel_id",
        "telescope_type",
        "channel_type",
        "acquisition_mode",
        "channel_subtype",
        "zero_bin",
        "dead_time",
        "background_low_bin",
        "background_high_bin",
        "G",
        "H",
        "emitted_wavelength",
        "detected_wavelength",
        "channel_bandwidth",
        "bins",
        "data_acquisition_range",
        "range_resolution",
        "laser_repetition_rate",
    ],
    "polarization_calibration": [
        "ch_r",
        "ch_t",
        "K",
        "R_to_T_transmission_ratio",
        "eta",
    ],
    "gluing": [
        "ch_n",
        "ch_f",
    ],
    "water_vapour": [
        "ch_w",
        "ch_v",
        "wv_calibration_factor",
    ],
    "temperature": [
        "ch_h",
        "ch_l",
        "alpha_prime",
        "beta_prime",
        "gamma_prime",
    ],
}


# Full settings template: emitted INI section names followed by the explicit
# schema-key whitelist for each section.
SETTINGS_TEMPLATE_SECTIONS = {
    "qck": "quicklooks",
    "bgd": "background",
    "qck_vldr": "quicklooks_vldr",
    "drk": "dark",
    "ray": "rayleigh_fit",
    "tlc": "quadrant_telecover",
    "tlc_rin": "ring_telecover",
    "pcb": "polarization_calibration",
}

SETTINGS_TEMPLATE_KEYS = {
    "qck": [
        "t_lims",
        "t_tick",
        "x_lims",
        "x_tick",
        "y_lims",
        "y_max_zone",
        "use_log_y_scale",
        "smooth",
        "smoothing_range",
        "smoothing_window",
        "smoothing_exponential",
        "select_channels",
        "exclude_wavelength",
        "exclude_telescope_type",
        "exclude_channel_type",
        "exclude_acquisition_mode",
        "exclude_channel_subtype",
    ],
    "bgd": [
        "t_lims",
        "t_tick",
        "y_lims",
        "select_channels",
        "exclude_wavelength",
        "exclude_telescope_type",
        "exclude_channel_type",
        "exclude_acquisition_mode",
        "exclude_channel_subtype",
    ],
    "qck_vldr": [
        "t_lims",
        "t_tick",
        "x_lims",
        "x_tick",
        "y_lims",
        "y_max_zone",
        "use_log_y_scale",
        "smooth",
        "smoothing_range",
        "smoothing_window",
        "smoothing_exponential",
        "include_pairs",
        "exclude_wavelength",
        "exclude_telescope_type",
        "exclude_pair_type",
        "exclude_acquisition_mode",
        "exclude_channel_subtype",
    ],
    "drk": [
        "stats_range",
        "far_range_region",
        "averaging_period",
        "relative_molecular_deviation",
        "smooth",
        "smoothing_range",
        "smoothing_window",
        "smooth_rc",
        "smoothing_range_rc",
        "smoothing_window_rc",
        "select_channels",
        "exclude_wavelength",
        "exclude_telescope_type",
        "exclude_channel_type",
        "exclude_acquisition_mode",
        "exclude_channel_subtype",
    ],
    "ray": [
        "x_lims",
        "x_tick",
        "y_lims",
        "use_lin_y_scale",
        "normalization_region",
        "molecular_mask_region",
        "molecular_mask_window",
        "molecular_mask_window_step",
        "rsem_threshold",
        "first_derivative_threshold",
        "second_derivative_threshold",
        "shapiro_wilk_threshold",
        "cross_criterion_threshold",
        "durbin_watson_threshold",
        "absolute_extinction_error_threshold",
        "isolated_point_radius",
        "isolated_point_neighbour_threshold",
        "smooth",
        "smoothing_range",
        "smoothing_window",
        "select_channels",
        "exclude_wavelength",
        "exclude_telescope_type",
        "exclude_channel_type",
        "exclude_acquisition_mode",
        "exclude_channel_subtype",
    ],
    "tlc": [
        "plot_raw_signals",
        "use_last_sector",
        "normalization_region",
        "relative_deviation_limit",
        "near_range_upper_limit",
        "smooth",
        "smoothing_window",
        "select_channels",
        "exclude_wavelength",
        "exclude_telescope_type",
        "exclude_channel_type",
        "exclude_acquisition_mode",
        "exclude_channel_subtype",
    ],
    "tlc_rin": [
        "plot_raw_signals",
        "use_last_sector",
        "normalization_region",
        "relative_deviation_limit",
        "near_range_upper_limit",
        "smooth",
        "smoothing_window",
        "select_channels",
        "exclude_wavelength",
        "exclude_telescope_type",
        "exclude_channel_type",
        "exclude_acquisition_mode",
        "exclude_channel_subtype",
    ],
    "pcb": [
        "x_lims_signals",
        "x_tick_signals",
        "y_lims_signals",
        "x_lims_calibration",
        "x_tick_calibration",
        "y_lims_calibration",
        "x_lims_rayleigh",
        "x_tick_rayleigh",
        "y_lims_rayleigh",
        "calibration_region",
        "rayleigh_region",
        "pldr_error_threshold",
        "smooth",
        "smoothing_range",
        "smoothing_window",
        "smoothing_exponential",
    ],
}


# Intercomparison template blocks.
INTERCOMPARISON_TEMPLATE_KEYS = {
    "general": [
        "output_folder",
        "overwrite_output",
        "default_qa_test",
        "default_signal_source",
        "default_signal_error_source",
        "default_pair_source",
        "default_pair_error_source",
        "vertical_scale",
        "vertical_method",
        "vertical_bin_width",
        "first_bin_left_edge",
        "vertical_min",
        "vertical_max",
        "plot_native_scale",
        "slice_measurement",
        "exclude_measurement",
        "default_channel_background_correction",
        "default_channel_background_region",
        "default_channel_normalisation",
        "default_channel_normalisation_region",
        "default_channel_normalise_to_molecular",
        "default_channel_plot_molecular",
        "default_pair_background_correction",
        "default_pair_background_region",
        "default_pair_normalisation",
        "default_pair_normalisation_region",
        "default_pair_plot_molecular",
        "dpi",
        "color_reduction",
    ],
    "plotting": [
        "channel_x_lims",
        "pair_x_lims",
        "x_tick",
        "channel_difference_y_lims",
        "pair_difference_y_lims",
        "channel_y_lims",
        "channel_smooth",
        "channel_smoothing_range",
        "channel_smoothing_window",
        "pair_y_lims",
        "pair_smooth",
        "pair_smoothing_range",
        "pair_smoothing_window",
    ],
    "dataset": [
        "stage_path",
        "reference",
        "system_label",
        "dataset_label",
        "qa_test",
        "signal_source",
        "signal_error_source",
        "pair_source",
        "pair_error_source",
    ],
    "channel_group": [
        "label",
        "background_correction",
        "background_region",
        "normalisation",
        "normalisation_region",
        "normalise_to_molecular",
        "plot_molecular",
        "vertical_bin_width",
        "smooth",
        "smoothing_range",
        "smoothing_window",
        "x_lims",
        "x_tick",
        "y_lims",
        "difference_y_lims",
        "use_log_y_scale",
    ],
    "pair_group": [
        "label",
        "background_correction",
        "background_region",
        "normalisation",
        "normalisation_region",
        "plot_molecular",
        "vertical_bin_width",
        "smooth",
        "smoothing_range",
        "smoothing_window",
        "x_lims",
        "x_tick",
        "y_lims",
        "difference_y_lims",
        "use_log_y_scale",
    ],
}

# ---------------------------------------------------------------------------
# Beginner initialization template
# ---------------------------------------------------------------------------
# Section names must match the strict lowercase initialization parser sections.
# Keys must exist in parse_init_file.SCHEMA.

BEGINNER_INIT_TEMPLATE_SECTIONS = {
    "configuration": [
        "scc_configuration_id",
        "export_hoi_cfg",
    ],
    "explicit_paths": [
        "parent_folder",
        "atlas_configuration_file",
        "atlas_settings_file",
        "radiosonde_folder",
        "radiosonde_file",
        "output_folder",
    ],
    "general_options": [
        "process",
        "process_qck",
        "process_bgd",
        "process_vldr",
        "process_dedicated_dark",
    ],
    "trimming_options": [
        "max_height_agl",
        "slice_measurement",
        "exclude_measurement",
    ],
    "parsing_options": [
        "rsonde_station_name",
        "rsonde_station_wmo_id",
        "cloudnet_station_name",
    ],
}


# ---------------------------------------------------------------------------
# Beginner configuration template
# ---------------------------------------------------------------------------
# Section names must match the user-facing configuration INI sections.
# Keys must exist in parse_config_file.SCHEMA.

BEGINNER_CONFIG_TEMPLATE_SECTIONS = {
    "System": [
        "station_id",
        "lidar_name",
        "station_name",
        "station_altitude",
        "station_latitude",
        "station_longitude",
        "zenith_angle",
        "azimuth_angle",
    ],
    "Channels": [
        "recorder_channel_id",
        "scc_channel_id",
        "telescope_type",
        "channel_type",
        "channel_subtype",
        "zero_bin",
        "dead_time",
        "background_low_bin",
        "background_high_bin",
        "acquisition_mode",
        "detected_wavelength",
        "emitted_wavelength",
        "channel_bandwidth",
        "bins",
        "range_resolution",
        "laser_repetition_rate",
        "G",
        "H",
    ],
    "polarization_calibration": [
        "ch_r",
        "ch_t",
        "K",
        "R_to_T_transmission_ratio",
        "eta",
    ],
    "gluing": [
        "ch_n",
        "ch_f",
    ],
    "water_vapour": [
        "ch_w",
        "ch_v",
        "wv_calibration_factor",
    ],
    "temperature": [
        "ch_h",
        "ch_l",
        "alpha_prime",
        "beta_prime",
        "gamma_prime",
    ],
}


# ---------------------------------------------------------------------------
# Beginner settings template
# ---------------------------------------------------------------------------
# Top-level keys must match parse_settings_file.SCHEMA groups.
# Values are lists of keys inside each settings schema group.

BEGINNER_SETTINGS_TEMPLATE_KEYS = {
    "qck": [
        "x_lims",
        "x_tick",
        "y_lims",
        "use_log_y_scale",
        "smooth",
        "smoothing_window",
        "select_channels",
        "exclude_wavelength",
    ],
    "qck_vldr": [
        "x_lims",
        "x_tick",
        "y_lims",
        "use_log_y_scale",
        "smooth",
        "smoothing_window",
        "include_pairs",
        "exclude_wavelength",
    ],
    "ray": [
        "x_lims",
        "x_tick",
        "y_lims",
        "normalization_region",
        "molecular_mask_region",
        "smooth",
        "smoothing_window",
        "select_channels",
        "exclude_wavelength",
    ],
    "tlc": [
        "plot_raw_signals",
        "use_last_sector",
        "normalization_region",
        "relative_deviation_limit",
        "near_range_upper_limit",
        "smooth",
        "smoothing_window",
        "select_channels",
        "exclude_wavelength",
    ],
    "tlc_rin": [
        "plot_raw_signals",
        "use_last_sector",
        "normalization_region",
        "relative_deviation_limit",
        "near_range_upper_limit",
        "smooth",
        "smoothing_window",
        "select_channels",
        "exclude_wavelength",
    ],
    "pcb": [
        "x_lims_signals",
        "x_lims_calibration",
        "x_lims_rayleigh",
        "calibration_region",
        "rayleigh_region",
        "pldr_error_threshold",
        "smooth",
        "smoothing_window",
    ],
}
